### ISSUE TITLE
Reduce the number of lines per method

### ISSUE THREAD

**Issue by kbrock** [ManageIQ/optimist#41]
Per @student The question is whether it made sense to split up the gem into multiple files and classes.
The opt method is 111 lines and parse is 138.

First pass would be to determine if makes sense to represent each option using a class instead of the various options. There are far too many if blocks for my taste. Not sure where it would go from there.

Not sure if anyone has any extra comments and/or concerns.

**Comment by Fryguy** [comment]
Multiple classes: yes.  Multiple files: no.  Since the beginning trollop has always stated "Single file. Throw it in lib/ if you don't want to make it a Rubygem dependency."  I'd rather we didn't change that.  In fact, a [recent issue](https://github.com/ManageIQ/trollop/issues/21) was raised when we broke that rule, so people are aware of it.

**Comment by magicalbanana** [comment]
I think it's better to keep it this way, I agree with @Fryguy about multiple classes but I love the single file option it offers. It's just easier to maintain and what not.

**Comment by kbrock** [comment]
@magicalbanana thanks for your feedback. I think we're all in agreement that possibly multiple classes may simplify things

**Comment by mfeifer** [comment]
@kbrock is this still relevant?

**Comment by kbrock** [comment]
splitting each option into a class may make sense. It would require a lot of change.

Keeping the structure as it is for now
