### ISSUE TITLE
Rainbow integration

### ISSUE THREAD

**Issue by ioquatix** [ManageIQ/optimist#72]
I thought it would be nice if Trollop could optionally integrate with Rainbow for coloured output. Would you be interested in a PR?

**Comment by kbrock** [comment]
Hello @ioquatix,

If it doesn't add to the list of dependencies, or change too many lines of code, then that sounds great.

**Comment by rubyFeedback** [comment]
On a side note - not so relevant to the discussion here, but I have an old legacy application (also using trolloc) that makes use of rainbow integration. In particular I combine it with "animated" ascii, where different "frames" are sent into a bin/rainbow file that in turns colourizes this. It's quite funny to look at (although a bit useless too). Right now the old legacy code uses trollop - I have not yet looked into optimist yet (since the code was written mostly by someone else; I am just pretending to maintain that legacy code).

**Comment by ioquatix** [comment]
I ended up doing something completely different. So, I'm happy to close this issue.
